version: '3'
services:
  nginx_v3:
    container_name: mynginx_v3
    image: nikhomdoc/sugar_nginx2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../client:/usr/share/nginx/html
      - ./config:/etc/nginx/conf.d
      - ../letsencrypt:/etc/letsencrypt

networks: 
    default: 
        external: 
            name: external-network-v3